// CommuteDashboards/vueJavascript/src/components/CommuteAnalysis.vue
<template>
	<BContainer fluid class='px-0'>
		<BRow>
			<ToggleBar />
			<!-- <h2>ToggleBar</h2> -->
		</BRow>
		<BRow>
			<CommuteDurationsGraph />
			<!-- <h2>Graph</h2> -->
		</BRow>
		<BRow>
			<CommuteTable />
			<!-- <h2>Table</h2> -->
		</BRow>
	</BContainer>
</template>


<script setup>
import { BRow, BContainer } from 'bootstrap-vue-next'
import ToggleBar from './ToggleBar.vue'
import CommuteDurationsGraph from './CommuteDurationsGraph.vue'
import CommuteTable from './CommuteTable/CommuteTable.vue'

</script>

// CommuteDashboards/reactTypescript/src/components/CommuteAnalysis.tsx
import Stack from 'react-bootstrap/Stack';

import ToggleBar from './ToggleBar.jsx'
import CommuteDurationsGraph from './CommuteDurationsGraph.jsx'
import CommuteTable from './CommuteTable.jsx'

function CommuteAnalysis() {
	
	return (
		<>
			<Stack className="mx-auto">
				<div className="p-1">
					<ToggleBar />
				</div>
				<div className="p-3">
					<CommuteDurationsGraph />
				</div>
				<div className="p-2">
					<CommuteTable />
				</div>
			</Stack>
		</>
	)
}

export default CommuteAnalysis
