// CommuteDashboards/vueJavascript/src/components/ToggleBar.vue
<template>
		<BButtonToolbar justify>
			<BButtonGroup aria-label="Weekday toggle bar">
				<!-- v-for... -->
				<BButton variant='secondary' v-for='day in dayNames' @click='handleClick(day[0])' :key='day[0]'>
					{{ day[1] }}
				</BButton>
				<!-- {dayNames.map((day) => {
					return (
						<Button key={day[0]} variant="secondary" onClick={handleClick} day={day[0]}>{day[1]}</Button>
					)
				})} -->
			</BButtonGroup>
			<!-- TODO: vue buttons -->
			<BButton variant='secondary' @click='handleToggleMorning'>{{ showMorning ? "Showing Morning" : "Showing Evening" }}</BButton>
			<!-- <Button className="ms-auto" variant="secondary" onClick={handleToggleMorning} >{showMorning ? "Showing Morning" : "Showing Evening"}</Button> -->
		</BButtonToolbar>

</template>

<script setup>
import { ref, inject, watch, onMounted } from 'vue'
import { BButton, BButtonGroup, BButtonToolbar } from 'bootstrap-vue-next'

const activeDay = inject('activeDay')
const days = inject('weekdays')
const dayNames = ref()
const showMorning = inject('showMorning')

function mapData() {
	console.log('watching days, val:')
	console.log(days.value)
	if (!activeDay.value || !days.value || !days.value.includes(activeDay.value)) return
	let dateMap = days.value.map(day => {
		let name = new Date(day).toDateString()
		name = name.substring(4, name.length - 5)
		console.log(day + ' ' + name)
		return [day, name] 
	})
	console.log('dateMap:')
	console.log(dateMap)
	dayNames.value = dateMap
	console.log(dayNames.value)
}

onMounted(() => {
	mapData()
})

watch(days, () => {
	mapData()
})

//TODO: capture click event in vue
function handleClick(timestamp) {
	console.log('old ' + activeDay.value)
	console.log('new ' + timestamp)
	// console.log(timestamp)

	activeDay.value = timestamp
}
function handleToggleMorning(event) {
	showMorning.value = !showMorning.value
}


</script>

// CommuteDashboards/reactTypescript/src/components/ToggleBar.tsx
import { useState, useEffect, useContext } from 'react'

import Button from 'react-bootstrap/Button';
import ButtonGroup from 'react-bootstrap/ButtonGroup';
import Stack from 'react-bootstrap/Stack'

import { ActiveDayContext, WeekdaysContext, ShowMorningContext} from './CommuteDataContext/CommuteDataContext.jsx'

export default function ToggleBar() {
	const {activeDay, setActiveDay} = useContext(ActiveDayContext)
	const days = useContext(WeekdaysContext)

	const [dayNames, setDayNames] = useState<(string | number)[][]>()
	const {showMorning, setShowMorning} = useContext(ShowMorningContext)


	useEffect(() => {
		if (!activeDay || !days || !days.includes(activeDay)) return
		let dateMap = days.map(day => {
			let name = new Date(day).toDateString()
			name = name.substring(4, name.length - 5)
			console.log(day + ' ' + name)
			return [day, name] 
		})
		console.log('dateMap:')
		console.log(dateMap)
		setDayNames(dateMap)
	}, [days])

	function handleClick(event: { currentTarget: { getAttribute: (arg0: string) => string; }; }) {
		console.log('old',activeDay)
		console.log('new', event.currentTarget.getAttribute('day'))
		setActiveDay(parseInt(event.currentTarget.getAttribute('day')))
	}
	function handleToggleMorning() {
		setShowMorning(!showMorning)
	}

	return (
		<>
			{dayNames && (
				<Stack direction="horizontal">
					<ButtonGroup aria-label="Basic example">
						{dayNames.map((day) => {
								return (
									// @ts-ignore
									<Button key={day[0]} variant="secondary" onClick={handleClick} day={day[0]}>{day[1]}</Button>
								)
							})
						}
					</ButtonGroup>
					<Button className="ms-auto" variant="secondary" onClick={handleToggleMorning} >{showMorning ? "Showing Morning" : "Showing Evening"}</Button>
				</Stack>
			)}
		</>
	)
}
